version: "3.9"
services:
  mysql:
    image: mysql
    container_name: bd_mysql
    ports:
      - 23306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=manuel
      - MYSQL_PASSWORD=manuel
      - MYSQL_DATABASE=empresa
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8800:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1



